name: Scheduled Tasks
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-go-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"

      - name: Install dependencies
        run: go mod tidy

      - name: Build binary
        run: go build -o main

      - name: Run task
        run: |
          ./main -task=oricon_ranking && \
          ./main -task=github_trending && \
          ./main -task=vocaloid_ranking
        env:
          DISCORD_CHAT_WEBHOOK_URL: ${{ secrets.DISCORD_CHAT_WEBHOOK_URL }}
          DISCORD_SYS_WEBHOOK_URL: ${{ secrets.DISCORD_SYS_WEBHOOK_URL }}
